spring:
  application:
    name: backend

  # ===== Virtual Threads =====
  threads:
    virtual:
      enabled: true

  # ===== DataSource (MariaDB) =====
  datasource:
    url: jdbc:mariadb://localhost:3306/DEMO
    username: ADMIN
    password: ADMIN_P@SSWORD
    driver-class-name: org.mariadb.jdbc.Driver

  # ===== JPA / Hibernate =====
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
